package it.polito.master.ap.group6.ecommerce.orderservice.miscellaneous

enum class OrderLoggerStatus {
    PENDING,
    CHECK_WALLET_FAILED,
    CHECK_WALLET_COMPLETED,
    SUBMIT_ORDER_FAILED_WAITING_FOR_RECHARGE,
    SUBMIT_ORDER_FAILED,
    SUBMIT_ORDER_COMPLETED,
    COMPLETE_TRANSACTION_FAILED_WAITING_FOR_RESTORE,
    COMPLETE_TRANSACTION_FAILED,
    COMPLETE_TRANSACTION_COMPLETED,
    PAID,
    DELIVERING,
    DELIVERED,
    CANCELED_WAITING_FOR_RECHARGE,
    CANCELED_WAITING_FOR_RESTORE,
    CANCELED,
}
