package it.polito.master.ap.group6.ecommerce.warehouseservice.repositories

import it.polito.master.ap.group6.ecommerce.warehouseservice.model.DeliveryLog
import it.polito.master.ap.group6.ecommerce.warehouseservice.model.Product
import org.springframework.data.mongodb.repository.MongoRepository
import org.springframework.data.mongodb.repository.Query
import org.springframework.stereotype.Repository
import java.util.*

@Repository
interface DeliveryLogRepository: MongoRepository<DeliveryLog, String> {

    // Query automatically generated by Spring looking at the method declaration
    fun getDeliveryLogByOrderID(orderID: String) : Optional<DeliveryLog>

}
